# Generated by Django 5.2.17 on 2026-09-13 08:23

import django.core.validators
import django.db.models.deletion
import observations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='שם בעברית')),
                ('name_en', models.CharField(blank=True, max_length=180, verbose_name='שם באנגלית')),
            ],
            options={
                'verbose_name': 'מדינה',
                'verbose_name_plural': 'מדינות',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='שם בעברית')),
                ('name_en', models.CharField(blank=True, max_length=180, verbose_name='שם באנגלית')),
            ],
            options={
                'verbose_name': 'ים',
                'verbose_name_plural': 'ימים',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=200, unique=True, verbose_name='שם מדעי')),
                ('name_he', models.CharField(blank=True, max_length=200, verbose_name='שם בעברית')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='שם באנגלית')),
                ('source_id', models.CharField(blank=True, max_length=200, verbose_name='מזהה מקור לייבוא')),
            ],
            options={
                'verbose_name': 'מין',
                'verbose_name_plural': 'מינים',
                'ordering': ['scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='שם בעברית')),
                ('name_en', models.CharField(blank=True, max_length=180, verbose_name='שם באנגלית')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.country', verbose_name='מדינה')),
                ('sea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.sea', verbose_name='ים')),
            ],
            options={
                'verbose_name': 'אזור',
                'verbose_name_plural': 'אזורים',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='שם לתצוגה')),
                ('macro_diver', models.BooleanField(default=False, verbose_name='מעוניין במציאת שותפים לצלילת מאקרו')),
                ('visible_to_members', models.BooleanField(default=False, verbose_name='הצגת הפרופיל למשתמשים רשומים')),
                ('bio', models.TextField(blank=True, max_length=1500, verbose_name='על עצמי')),
                ('countries', models.ManyToManyField(blank=True, to='observations.country', verbose_name='מדינות צלילה')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('regions', models.ManyToManyField(blank=True, to='observations.region', verbose_name='אזורי צלילה')),
            ],
            options={
                'verbose_name': 'פרופיל',
                'verbose_name_plural': 'פרופילים',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='שם בעברית')),
                ('name_en', models.CharField(blank=True, max_length=180, verbose_name='שם באנגלית')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.region', verbose_name='אזור')),
            ],
            options={
                'verbose_name': 'אתר צלילה',
                'verbose_name_plural': 'אתרי צלילה',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_other', models.CharField(blank=True, max_length=200, verbose_name='מין אחר')),
                ('country_other', models.CharField(blank=True, max_length=200, verbose_name='מדינה אחרת')),
                ('region_other', models.CharField(blank=True, max_length=200, verbose_name='אזור אחר')),
                ('site_other', models.CharField(blank=True, max_length=200, verbose_name='אתר צלילה אחר')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='שנה')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='חודש')),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='יום')),
                ('depth', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='עומק במטרים')),
                ('video_url', models.URLField(validators=[observations.models.youtube_id], verbose_name='קישור YouTube')),
                ('image', models.ImageField(blank=True, upload_to='observations/', verbose_name='תמונה חלופית (רשות)')),
                ('status', models.CharField(choices=[('pending', 'ממתינה לאישור'), ('published', 'מפורסמת')], default='pending', max_length=20, verbose_name='מצב פרסום')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('source_id', models.CharField(blank=True, max_length=200, verbose_name='מזהה מקור לייבוא')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='observations.country', verbose_name='מדינה')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to=settings.AUTH_USER_MODEL, verbose_name='יוצר')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='observations.region', verbose_name='אזור')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='observations.site', verbose_name='אתר צלילה')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='observations.species', verbose_name='מין')),
            ],
            options={
                'verbose_name': 'תצפית',
                'verbose_name_plural': 'תצפיות',
                'ordering': ['-created_at'],
            },
        ),
    ]
