# Generated by Django 5.2.17 on 2026-09-13 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_rename_observation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['-created_at'], 'verbose_name': 'דגימה / תצפית', 'verbose_name_plural': 'Samples — דגימות ותצפיות'},
        ),
        migrations.AddField(
            model_name='sample',
            name='gallery_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sample',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sample',
            name='title',
            field=models.CharField(blank=True, max_length=240, verbose_name='כותרת הגלריה'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='שנה'),
        ),
        migrations.AlterModelTable(
            name='sample',
            table='samples',
        ),
    ]
