# Generated by Django 5.2.17 on 2026-09-14 06:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_alter_sample_options_sample_gallery_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiveTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=uuid.uuid4, max_length=40, unique=True, verbose_name='קוד מסע')),
                ('title', models.CharField(max_length=400, verbose_name='שם המסע')),
                ('source_sort', models.CharField(blank=True, max_length=100, verbose_name='מיון במקור')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='שנה')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='חודש')),
                ('start_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='יום התחלה')),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='מספר ימים')),
                ('country_name', models.CharField(blank=True, max_length=180, verbose_name='מדינה כפי שנרשמה במקור')),
                ('region_name', models.CharField(blank=True, max_length=180, verbose_name='אזור כפי שנרשם במקור')),
                ('reserve', models.CharField(blank=True, max_length=180, verbose_name='שמורה / אתר')),
                ('sea_name', models.CharField(blank=True, max_length=180, verbose_name='ים')),
                ('photographer', models.CharField(blank=True, max_length=180, verbose_name='צלם')),
                ('species_count', models.PositiveIntegerField(blank=True, help_text='מספר מדווח לכל המסע; אינו מספר הסרטונים באתר. השאר ריק אם אינו ידוע.', null=True, verbose_name='מספר מינים שנצפו במסע')),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'מסע צלילה',
                'verbose_name_plural': 'מסעות צלילה',
                'db_table': 'dive_trips',
                'ordering': ['-year', '-month', 'title'],
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='kind',
            field=models.CharField(choices=[('species', 'מין יחיד'), ('collection', 'אוסף מינים / מסע צלילה')], default='species', max_length=20, verbose_name='סוג הסרטון'),
        ),
        migrations.AddField(
            model_name='sample',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='observations.divetrip', verbose_name='מסע צלילה'),
        ),
    ]
