# Generated by Django 5.2.17 on 2026-09-14 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_divetrip_sample_kind_sample_trip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('kind', 'species'), ('status', 'published')), fields=('species', 'region'), name='unique_published_species_region'),
        ),
    ]
