# Generated by Django 5.2.17 on 2026-09-14 14:21

import observations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_sample_unique_published_species_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='video_url',
            field=models.URLField(blank=True, validators=[observations.models.youtube_id], verbose_name='קישור YouTube'),
        ),
    ]
