# Generated by Django 5.2.17 on 2026-09-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_sample_transfer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='accepted_genus',
            field=models.TextField(blank=True, verbose_name='Accepted genus — סוג מקובל'),
        ),
        migrations.AddField(
            model_name='species',
            name='accepted_species',
            field=models.TextField(blank=True, verbose_name='Accepted species — מין מקובל'),
        ),
        migrations.AddField(
            model_name='species',
            name='author',
            field=models.TextField(blank=True, verbose_name='Author — מחבר ושנת תיאור'),
        ),
        migrations.AddField(
            model_name='species',
            name='common_name',
            field=models.TextField(blank=True, verbose_name='Common name — שם נפוץ'),
        ),
        migrations.AddField(
            model_name='species',
            name='distribution',
            field=models.TextField(blank=True, verbose_name='Distribution — תפוצה'),
        ),
        migrations.AddField(
            model_name='species',
            name='family',
            field=models.TextField(blank=True, verbose_name='Family — משפחה'),
        ),
        migrations.AddField(
            model_name='species',
            name='formatted_author',
            field=models.TextField(blank=True, verbose_name='Formatted author — מחבר מעוצב'),
        ),
        migrations.AddField(
            model_name='species',
            name='genus',
            field=models.TextField(blank=True, verbose_name='Genus — סוג'),
        ),
        migrations.AddField(
            model_name='species',
            name='language',
            field=models.TextField(blank=True, verbose_name='Language — שפה'),
        ),
        migrations.AddField(
            model_name='species',
            name='order',
            field=models.TextField(blank=True, verbose_name='Order — סדרה'),
        ),
        migrations.AddField(
            model_name='species',
            name='species',
            field=models.TextField(blank=True, verbose_name='Species — שם המין'),
        ),
        migrations.AddField(
            model_name='species',
            name='superfamily',
            field=models.TextField(blank=True, verbose_name='Superfamily — על־משפחה'),
        ),
        migrations.AddField(
            model_name='species',
            name='transliteration',
            field=models.TextField(blank=True, verbose_name='Transliteration — תעתיק'),
        ),
        migrations.AlterField(
            model_name='species',
            name='source_id',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='מזהה מקור לייבוא'),
        ),
    ]
