# Generated by Django 5.2.17 on 2026-09-14 15:17

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_species_accepted_genus_species_accepted_species_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': [models.OrderBy(django.db.models.functions.comparison.NullIf('phylogenetic_order', models.Value('')), nulls_last=True), 'scientific_name'], 'verbose_name': 'מין', 'verbose_name_plural': 'מינים'},
        ),
        migrations.AddField(
            model_name='species',
            name='full_species_name_with_order',
            field=models.TextField(blank=True, verbose_name='שם מלא עם סדר — מהאקסל'),
        ),
        migrations.AddField(
            model_name='species',
            name='phylogenetic_order',
            field=models.CharField(blank=True, max_length=40, verbose_name='סדר אבולוציוני'),
        ),
        migrations.AddField(
            model_name='species',
            name='reference_author',
            field=models.TextField(blank=True, verbose_name='מחבר נוסף / מקור זיהוי — Author באקסל'),
        ),
    ]
