# Generated by Django 5.2.17 on 2026-09-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0009_alter_species_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='מזהה')),
                ('image', models.ImageField(upload_to='site/', verbose_name='תמונה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן')),
            ],
            options={
                'verbose_name': 'תמונת אתר',
                'verbose_name_plural': 'תמונות אתר',
            },
        ),
    ]
