# Generated by Django 5.2.17 on 2026-09-16 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0010_site_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='divetrip',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dive_trips', to='observations.country', verbose_name='מדינה'),
        ),
        migrations.AddField(
            model_name='divetrip',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dive_trips', to='observations.region', verbose_name='אזור'),
        ),
        migrations.CreateModel(
            name='SpeciesArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.country', verbose_name='מדינה')),
                ('defining_sample', models.ForeignKey(blank=True, help_text='הדגימה שתמונתה או שרטון היוטיוב שלה יוצגו בכרטיס המין בגלריה. ניתן לבחור דגימה אחרת מבין דגימות המין באזור זה.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='observations.sample', verbose_name='דגימה מגדירה')),
                ('sea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.sea', verbose_name='ים')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='observations.species', verbose_name='מין')),
            ],
            options={
                'verbose_name': 'מין באזור',
                'verbose_name_plural': 'מינים באזורים',
                'constraints': [models.UniqueConstraint(fields=('species', 'country', 'sea'), name='unique_species_area')],
            },
        ),
    ]
