# Generated by Django 5.2.17 on 2026-09-16 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0012_backfill_trip_locations_and_species_areas'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sample',
            name='unique_published_species_region',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='country',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='country_other',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='month',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='region',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='region_other',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='year',
        ),
        migrations.AlterField(
            model_name='sample',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='observations.divetrip', verbose_name='מסע צלילה'),
        ),
    ]
