# Generated by Django 5.2.17 on 2026-09-23 06:28

import django.db.models.deletion
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0013_trim_sample_location_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='משפחה')),
                ('name_he', models.CharField(blank=True, max_length=150, verbose_name='שם בעברית')),
                ('sub_family', models.CharField(blank=True, max_length=150, verbose_name='תת-משפחה')),
                ('taxonomic_order', models.CharField(blank=True, max_length=40, verbose_name='סדר טקסונומי')),
            ],
            options={
                'verbose_name': 'משפחה (טקסונומיה)',
                'verbose_name_plural': 'משפחות (טקסונומיה)',
                'ordering': [models.OrderBy(django.db.models.functions.comparison.NullIf('taxonomic_order', models.Value('')), nulls_last=True), 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxonOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='סדרה')),
                ('name_he', models.CharField(blank=True, max_length=150, verbose_name='שם בעברית')),
                ('sub_order', models.CharField(blank=True, max_length=150, verbose_name='תת-סדרה')),
                ('taxonomic_order', models.CharField(blank=True, max_length=40, verbose_name='סדר טקסונומי')),
            ],
            options={
                'verbose_name': 'סדרה (טקסונומיה)',
                'verbose_name_plural': 'סדרות (טקסונומיה)',
                'ordering': [models.OrderBy(django.db.models.functions.comparison.NullIf('taxonomic_order', models.Value('')), nulls_last=True), 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxonGenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='סוג')),
                ('name_he', models.CharField(blank=True, max_length=150, verbose_name='שם בעברית')),
                ('taxonomic_order', models.CharField(blank=True, max_length=40, verbose_name='סדר טקסונומי')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genera', to='observations.taxonfamily', verbose_name='משפחה')),
            ],
            options={
                'verbose_name': 'סוג (טקסונומיה)',
                'verbose_name_plural': 'סוגים (טקסונומיה)',
                'ordering': [models.OrderBy(django.db.models.functions.comparison.NullIf('taxonomic_order', models.Value('')), nulls_last=True), 'name'],
            },
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='families', to='observations.taxonorder', verbose_name='סדרה'),
        ),
    ]
