# Generated by Django 5.2.17 on 2026-09-23 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0014_taxonfamily_taxonorder_taxongenus_taxonfamily_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='שם בעברית')),
                ('name_en', models.CharField(blank=True, max_length=180, verbose_name='שם באנגלית')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='קוד')),
            ],
            options={
                'verbose_name': 'סוג דגימה',
                'verbose_name_plural': 'סוגי דגימה',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='defining_sample',
            field=models.ForeignKey(blank=True, help_text='הדגימה שתמונתה או סרטון היוטיוב שלה יוצגו בכותרת המשפחה בגלריה.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='observations.sample', verbose_name='דגימה מגדירה'),
        ),
        migrations.AddField(
            model_name='taxongenus',
            name='defining_sample',
            field=models.ForeignKey(blank=True, help_text='הדגימה שתמונתה או סרטון היוטיוב שלה יוצגו בכותרת הסוג ובאוסף המינים שלו בגלריה.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='observations.sample', verbose_name='דגימה מגדירה'),
        ),
        migrations.AddField(
            model_name='taxonorder',
            name='defining_sample',
            field=models.ForeignKey(blank=True, help_text='הדגימה שתמונתה או סרטון היוטיוב שלה יוצגו בכותרת הסדרה בגלריה.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='observations.sample', verbose_name='דגימה מגדירה'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='kind',
            field=models.CharField(choices=[('species', 'מין יחיד'), ('collection', 'אוסף מינים / מסע צלילה'), ('genus', 'סוג'), ('family', 'משפחה'), ('order', 'סדרה')], default='species', max_length=20, verbose_name='סוג הסרטון'),
        ),
    ]
