# Generated by Django 5.2.17 on 2026-09-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0015_samplekind_taxonfamily_defining_sample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonfamily',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='שם באנגלית'),
        ),
        migrations.AddField(
            model_name='taxongenus',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='שם באנגלית'),
        ),
        migrations.AddField(
            model_name='taxonorder',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='שם באנגלית'),
        ),
    ]
