# Generated by Django 5.2.17 on 2026-09-23 07:25

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0016_taxonfamily_name_en_taxongenus_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonfamily',
            options={'ordering': [models.OrderBy(django.db.models.functions.comparison.NullIf('taxonomic_order', models.Value('')), nulls_last=True), 'name', 'sub_family'], 'verbose_name': 'משפחה (טקסונומיה)', 'verbose_name_plural': 'משפחות (טקסונומיה)'},
        ),
        migrations.AlterModelOptions(
            name='taxonorder',
            options={'ordering': [models.OrderBy(django.db.models.functions.comparison.NullIf('taxonomic_order', models.Value('')), nulls_last=True), 'name', 'sub_order'], 'verbose_name': 'סדרה (טקסונומיה)', 'verbose_name_plural': 'סדרות (טקסונומיה)'},
        ),
        migrations.AlterField(
            model_name='taxonfamily',
            name='name',
            field=models.CharField(max_length=150, verbose_name='משפחה'),
        ),
        migrations.AlterField(
            model_name='taxonorder',
            name='name',
            field=models.CharField(max_length=150, verbose_name='סדרה'),
        ),
        migrations.AddConstraint(
            model_name='taxonfamily',
            constraint=models.UniqueConstraint(fields=('name', 'sub_family'), name='unique_taxonfamily_name_sub_family'),
        ),
        migrations.AddConstraint(
            model_name='taxonorder',
            constraint=models.UniqueConstraint(fields=('name', 'sub_order'), name='unique_taxonorder_name_sub_order'),
        ),
    ]
