# Generated by Django 5.2.17 on 2026-09-23 14:26

from django.db import migrations, models

# The old auto-seeded rows for the classic 4-way Nudibranchia suborder split, superseded by
# the more detailed taxon_order_reference groups (Doridina/Cladobranchia, further split into
# informal Hebrew-named groups) that build_taxonomy_tables now seeds. Nothing has ever linked
# a TaxonFamily to these specific rows (family->order linking only ever resolved to the blank-
# sub_order base row), so they're safe to remove outright.
OBSOLETE_NUDIBRANCHIA_SUB_ORDERS = ['Doridacea', 'Dendronotacea', 'Arminacea', 'Aeolidacea']


def remove_obsolete_nudibranchia_suborders(apps, schema_editor):
    TaxonOrder = apps.get_model('observations', 'TaxonOrder')
    TaxonOrder.objects.filter(name='Nudibranchia', sub_order__in=OBSOLETE_NUDIBRANCHIA_SUB_ORDERS).delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0017_taxon_suborder_subfamily_rows'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taxonorder',
            name='unique_taxonorder_name_sub_order',
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='superfamily',
            field=models.CharField(blank=True, max_length=150, verbose_name='על-משפחה'),
        ),
        migrations.AddConstraint(
            model_name='taxonorder',
            constraint=models.UniqueConstraint(fields=('name', 'sub_order', 'taxonomic_order'), name='unique_taxonorder_name_sub_order_taxonomic_order'),
        ),
        migrations.RunPython(remove_obsolete_nudibranchia_suborders, noop_reverse),
    ]
