# Generated by Django 5.2.17 on 2026-09-23 14:26

import json
from pathlib import Path

from django.db import migrations, models

# The old auto-seeded rows for the classic 4-way Nudibranchia suborder split, superseded by
# the more detailed taxon_order_reference groups (Doridina/Cladobranchia, further split into
# informal Hebrew-named groups) that build_taxonomy_tables now seeds. Nothing has ever linked
# a TaxonFamily to these specific rows (family->order linking only ever resolved to the blank-
# sub_order base row), so they're safe to remove outright.
OBSOLETE_NUDIBRANCHIA_SUB_ORDERS = ['Doridacea', 'Dendronotacea', 'Arminacea', 'Aeolidacea']


def migrate_taxon_order_rows(apps, schema_editor):
    TaxonOrder = apps.get_model('observations', 'TaxonOrder')
    TaxonOrder.objects.filter(name='Nudibranchia', sub_order__in=OBSOLETE_NUDIBRANCHIA_SUB_ORDERS).delete()

    # Every "base" order row (sub_order='') that build_taxonomy_tables auto-created under the
    # OLD scheme has its taxonomic_order derived ad hoc from Species.phylogenetic_order. The new
    # taxon_order_reference gives these same order names an authoritative, curated
    # taxonomic_order instead -- realign existing rows to it now (in place, keeping their pk and
    # any FKs pointing at them intact) rather than letting build_taxonomy_tables's next run
    # create a SECOND row with the same (name, sub_order='') pair but a different
    # taxonomic_order, which the plain order-text sync() (matched by name+sub_order only) can't
    # tell apart from the pre-existing row.
    supplement_path = Path(__file__).resolve().parent.parent / 'management' / 'commands' / 'data' / 'taxonomy_excel_supplement.json'
    if not supplement_path.exists():
        return
    reference = json.loads(supplement_path.read_text(encoding='utf-8')).get('taxon_order_reference', [])
    for entry in reference:
        if entry.get('sub_order', ''):
            continue  # only base rows could pre-exist from the old scheme
        row = TaxonOrder.objects.filter(name=entry['order_name'], sub_order='').first()
        if not row:
            continue
        changed = []
        new_taxonomic_order = entry.get('taxonomic_order', '')
        if new_taxonomic_order and row.taxonomic_order != new_taxonomic_order:
            row.taxonomic_order = new_taxonomic_order
            changed.append('taxonomic_order')
        if not row.name_he and entry.get('order_name_he'):
            row.name_he = entry['order_name_he']
            changed.append('name_he')
        if not row.name_en and entry.get('order_name_en'):
            row.name_en = entry['order_name_en']
            changed.append('name_en')
        if changed:
            row.save(update_fields=changed)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0017_taxon_suborder_subfamily_rows'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taxonorder',
            name='unique_taxonorder_name_sub_order',
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='superfamily',
            field=models.CharField(blank=True, max_length=150, verbose_name='על-משפחה'),
        ),
        migrations.AddConstraint(
            model_name='taxonorder',
            constraint=models.UniqueConstraint(fields=('name', 'sub_order', 'taxonomic_order'), name='unique_taxonorder_name_sub_order_taxonomic_order'),
        ),
        migrations.RunPython(migrate_taxon_order_rows, noop_reverse),
    ]
