# Generated by Django 5.2.17 on 2026-09-24 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0019_fix_family_order_links_to_specific_suborder_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='divetrip',
            name='article_pdf',
            field=models.FileField(blank=True, upload_to='articles/trips/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='מאמר (PDF)'),
        ),
        migrations.AddField(
            model_name='divetrip',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='תיאור באנגלית'),
        ),
        migrations.AddField(
            model_name='divetrip',
            name='description_he',
            field=models.TextField(blank=True, verbose_name='תיאור בעברית'),
        ),
        migrations.AddField(
            model_name='divetrip',
            name='kind',
            field=models.CharField(choices=[('dive', 'מסע צלילה'), ('thematic', 'אוסף נושאי')], default='dive', help_text='מסע צלילה רגיל, לעומת אוסף נושאי של מינים (למשל מינים מהגרים לספסיאניים) שאינו בהכרח צלילה בודדת.', max_length=20, verbose_name='סוג המסע'),
        ),
        migrations.AddField(
            model_name='divetrip',
            name='link',
            field=models.URLField(blank=True, verbose_name='קישור'),
        ),
        migrations.AddField(
            model_name='species',
            name='article_pdf',
            field=models.FileField(blank=True, upload_to='articles/species/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='מאמר (PDF)'),
        ),
        migrations.AddField(
            model_name='species',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='תיאור באנגלית'),
        ),
        migrations.AddField(
            model_name='species',
            name='description_he',
            field=models.TextField(blank=True, verbose_name='תיאור בעברית'),
        ),
        migrations.AddField(
            model_name='species',
            name='first_observed_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='שנת תצפית ראשונה'),
        ),
        migrations.AddField(
            model_name='species',
            name='food',
            field=models.TextField(blank=True, verbose_name='מזון'),
        ),
        migrations.AddField(
            model_name='species',
            name='habitat',
            field=models.TextField(blank=True, verbose_name='בית גידול'),
        ),
        migrations.AddField(
            model_name='species',
            name='is_migrant',
            field=models.BooleanField(default=False, verbose_name='מין מהגר'),
        ),
        migrations.AddField(
            model_name='species',
            name='last_observed_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='שנת תצפית אחרונה'),
        ),
        migrations.AddField(
            model_name='species',
            name='link',
            field=models.URLField(blank=True, verbose_name='קישור'),
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='article_pdf',
            field=models.FileField(blank=True, upload_to='articles/families/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='מאמר (PDF)'),
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='תיאור באנגלית'),
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='description_he',
            field=models.TextField(blank=True, verbose_name='תיאור בעברית'),
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='link',
            field=models.URLField(blank=True, verbose_name='קישור'),
        ),
        migrations.AddField(
            model_name='taxongenus',
            name='article_pdf',
            field=models.FileField(blank=True, upload_to='articles/genera/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='מאמר (PDF)'),
        ),
        migrations.AddField(
            model_name='taxongenus',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='תיאור באנגלית'),
        ),
        migrations.AddField(
            model_name='taxongenus',
            name='description_he',
            field=models.TextField(blank=True, verbose_name='תיאור בעברית'),
        ),
        migrations.AddField(
            model_name='taxongenus',
            name='link',
            field=models.URLField(blank=True, verbose_name='קישור'),
        ),
        migrations.AddField(
            model_name='taxonorder',
            name='article_pdf',
            field=models.FileField(blank=True, upload_to='articles/orders/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='מאמר (PDF)'),
        ),
        migrations.AddField(
            model_name='taxonorder',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='תיאור באנגלית'),
        ),
        migrations.AddField(
            model_name='taxonorder',
            name='description_he',
            field=models.TextField(blank=True, verbose_name='תיאור בעברית'),
        ),
        migrations.AddField(
            model_name='taxonorder',
            name='link',
            field=models.URLField(blank=True, verbose_name='קישור'),
        ),
    ]
