# Generated by Django 5.2.17 on 2026-09-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0020_divetrip_article_pdf_divetrip_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesarea',
            name='slug',
            field=models.SlugField(blank=True, help_text='נוצר אוטומטית משם המין+המדינה+הים בשמירה הראשונה. השאר ריק ליצירה אוטומטית, או הזן ידנית לדריסה.', max_length=220, null=True, unique=True, verbose_name='כתובת בעמוד'),
        ),
    ]
