# Generated by Django 5.2.17 on 2026-09-24 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0021_speciesarea_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='שם באנגלית'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+\\-()\\s]{5,30}$', 'מספר טלפון לא תקין.')], verbose_name='טלפון'),
        ),
    ]
