# Generated by Django 5.2.17 on 2026-09-24 15:12, then hand-edited to reorder the
# operations around a data migration: the two new English name fields must exist
# before we can copy anything into them, and the old fields must still exist while
# we read from them, so Add -> backfill -> Remove is the only safe order.

from django.db import migrations, models


def backfill_english_names(apps, schema_editor):
    """Split each profile's old free-text name_en ('Boaz') against display_name
    ('Boaz Liebes') into first_name_en/last_name_en ('Boaz' / 'Liebes'). Only runs
    when name_en was actually set -- display_name alone could be Hebrew (a person's
    chosen Hebrew public name with no English name ever recorded), and splitting
    Hebrew text into an "English name" field would be wrong, not just unhelpful."""
    Profile = apps.get_model('observations', 'Profile')
    for profile in Profile.objects.all():
        name_en = (profile.name_en or '').strip()
        if not name_en:
            continue
        display_name = (profile.display_name or '').strip()
        first, rest = name_en, ''
        if display_name.startswith(name_en):
            rest = display_name[len(name_en):].strip()
        profile.first_name_en = first
        profile.last_name_en = rest
        profile.save(update_fields=['first_name_en', 'last_name_en'])


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0022_profile_name_en_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name_en",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="שם פרטי באנגלית"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name_en",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="שם משפחה באנגלית"
            ),
        ),
        migrations.RunPython(backfill_english_names, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="profile",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="name_en",
        ),
    ]
