# Generated by Django 5.2.17 on 2026-09-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "observations",
            "0023_remove_profile_display_name_remove_profile_name_en_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Photographer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180, verbose_name="שם בעברית")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="שם באנגלית"
                    ),
                ),
            ],
            options={
                "verbose_name": "צלם",
                "verbose_name_plural": "צלמים",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reserve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180, verbose_name="שם בעברית")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="שם באנגלית"
                    ),
                ),
            ],
            options={
                "verbose_name": "שמורה / אתר",
                "verbose_name_plural": "שמורות / אתרים",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="divetrip",
            name="sea",
            field=models.ForeignKey(
                blank=True,
                help_text="נבחר מהטבלה. רלוונטי רק כאשר לא נבחר אזור -- כאשר יש אזור, הים נקבע ממנו אוטומטית.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dive_trips",
                to="observations.sea",
                verbose_name="ים",
            ),
        ),
        migrations.AlterField(
            model_name="divetrip",
            name="photographer",
            field=models.CharField(
                blank=True, max_length=180, verbose_name="צלם (טקסט חופשי)"
            ),
        ),
        migrations.AlterField(
            model_name="divetrip",
            name="reserve",
            field=models.CharField(
                blank=True, max_length=180, verbose_name="שמורה / אתר (טקסט חופשי)"
            ),
        ),
        migrations.AlterField(
            model_name="divetrip",
            name="sea_name",
            field=models.CharField(
                blank=True, max_length=180, verbose_name="ים כפי שנרשם במקור"
            ),
        ),
        migrations.AddField(
            model_name="divetrip",
            name="photographer_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dive_trips",
                to="observations.photographer",
                verbose_name="צלם",
            ),
        ),
        migrations.AddField(
            model_name="divetrip",
            name="reserve_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dive_trips",
                to="observations.reserve",
                verbose_name="שמורה / אתר",
            ),
        ),
    ]
