# Generated by Django 5.2.17 on 2026-09-25 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0025_prepopulate_reserve_photographer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="divetrip",
            name="reserve_fk",
        ),
        migrations.AddField(
            model_name="divetrip",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dive_trips",
                to="observations.site",
                verbose_name="שמורה / אתר",
            ),
        ),
        migrations.DeleteModel(
            name="Reserve",
        ),
    ]
