# Generated by Django 5.2.17 on 2026-09-28 10:33

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0030_sample_image_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': [models.OrderBy(django.db.models.functions.comparison.NullIf('phylogenetic_order', models.Value('')), nulls_last=True), 'scientific_name', 'undetermined_variant'], 'verbose_name': 'מין', 'verbose_name_plural': 'מינים'},
        ),
        migrations.AddField(
            model_name='species',
            name='undetermined_variant',
            field=models.CharField(blank=True, help_text='כשיש כמה מינים שונים מאותו סוג שכולם רשומים כ"sp." ברשימת המינים הרשמית, אפשר לסמן כאן אות (A, B, C…) כדי שהאתר יתייחס אליהם כמינים שונים -- בלי לשנות את השם המדעי הרשמי למעלה, כך שעדכון עתידי של רשימת המינים מהמקור הרשמי לא ידרוס את ההבחנה.', max_length=10, verbose_name='סימון מין לא מזוהה (sp.) — א׳/ב׳/A/B וכו׳'),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='שם מדעי'),
        ),
        migrations.AddConstraint(
            model_name='species',
            constraint=models.UniqueConstraint(fields=('scientific_name', 'undetermined_variant'), name='unique_species_scientific_name_variant'),
        ),
    ]
