# Generated by Django 5.2.17 on 2026-09-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0030_sample_image_hash'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='speciesarea',
            name='unique_species_area',
        ),
        migrations.AddField(
            model_name='sample',
            name='undetermined_variant',
            field=models.CharField(blank=True, help_text='כשיש כמה מינים שונים מאותו סוג שכולם רשומים כ"sp." ברשימת המינים הרשמית, אפשר לסמן כאן אות (A, B, C…) כדי שהאתר לא יאחד את התצפית הזו עם תצפיות של הצורה האחרת מאותו סוג בגלריה.', max_length=10, verbose_name='סימון מין לא מזוהה (sp.) — א׳/ב׳/A/B וכו׳'),
        ),
        migrations.AddField(
            model_name='speciesarea',
            name='undetermined_variant',
            field=models.CharField(blank=True, help_text='מועתק מתצפיות (Sample.undetermined_variant) שסומנו באותה אות -- שורה נפרדת לכל אות, כדי שלא תתמזג עם תצפיות של צורה אחרת מאותו סוג באותו אזור.', max_length=10, verbose_name='סימון מין לא מזוהה (sp.) — א׳/ב׳/A/B וכו׳'),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='שם מדעי'),
        ),
        migrations.AddConstraint(
            model_name='speciesarea',
            constraint=models.UniqueConstraint(fields=('species', 'country', 'sea', 'undetermined_variant'), name='unique_species_area'),
        ),
    ]
