# Generated by Django 5.2.17 on 2026-09-30 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0032_create_missing_genus_sp_placeholders'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='size_from',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='גודל אופייני מינימלי (מ״מ)'),
        ),
        migrations.AddField(
            model_name='species',
            name='size_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='גודל מקסימלי שנצפה (מ״מ)'),
        ),
        migrations.AddField(
            model_name='species',
            name='size_to',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='גודל אופייני מקסימלי (מ״מ)'),
        ),
    ]
