# Generated by Django 5.2.17 on 2026-10-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0039_species_scientific_name_not_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='family',
            field=models.CharField(blank=True, max_length=150, verbose_name='משפחה'),
        ),
        migrations.AddField(
            model_name='sample',
            name='genus',
            field=models.CharField(blank=True, max_length=150, verbose_name='סוג'),
        ),
        migrations.AddField(
            model_name='sample',
            name='identification_qualifier',
            field=models.CharField(blank=True, choices=[('cf.', 'cf. — דומה ל…'), ('aff.', 'aff. — קרוב ל…')], max_length=8, verbose_name='סימון זהות לא ודאית'),
        ),
        migrations.AddField(
            model_name='sample',
            name='life_stage',
            field=models.CharField(blank=True, choices=[('juv.', 'juv. — צעיר')], max_length=8, verbose_name='שלב חיים'),
        ),
        migrations.AddField(
            model_name='sample',
            name='order',
            field=models.CharField(blank=True, max_length=150, verbose_name='סדרה'),
        ),
    ]
