# Generated by Django 5.2.17 on 2026-10-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0041_sample_taxonomy_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationQualifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='שם בעברית')),
                ('name_en', models.CharField(blank=True, max_length=180, verbose_name='שם באנגלית')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='קיצור')),
            ],
            options={
                'verbose_name': 'סימון זהות לא ודאית',
                'verbose_name_plural': 'סימוני זהות לא ודאית (cf., aff.)',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LifeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='שם בעברית')),
                ('name_en', models.CharField(blank=True, max_length=180, verbose_name='שם באנגלית')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='קיצור')),
            ],
            options={
                'verbose_name': 'שלב חיים',
                'verbose_name_plural': 'שלבי חיים (juv.)',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sample',
            name='identification_qualifier',
            field=models.CharField(blank=True, max_length=8, verbose_name='סימון זהות לא ודאית'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='life_stage',
            field=models.CharField(blank=True, max_length=8, verbose_name='שלב חיים'),
        ),
    ]
