# Generated by Django 5.2.17 on 2026-10-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0050_accepted_names_for_four_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='depth_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='עומק מקסימלי (מ׳)'),
        ),
        migrations.AddField(
            model_name='species',
            name='depth_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='עומק מינימלי (מ׳)'),
        ),
        migrations.AddField(
            model_name='species',
            name='first_record_place_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='מקום התצפית הראשונה (אנגלית)'),
        ),
        migrations.AddField(
            model_name='species',
            name='first_record_place_he',
            field=models.CharField(blank=True, max_length=200, verbose_name='מקום התצפית הראשונה'),
        ),
        migrations.AddField(
            model_name='species',
            name='food_en',
            field=models.TextField(blank=True, verbose_name='מזון (אנגלית)'),
        ),
        migrations.AddField(
            model_name='species',
            name='habitat_en',
            field=models.TextField(blank=True, verbose_name='בית גידול (אנגלית)'),
        ),
        migrations.AddField(
            model_name='species',
            name='identification_en',
            field=models.TextField(blank=True, verbose_name='סימני זיהוי (אנגלית)'),
        ),
        migrations.AddField(
            model_name='species',
            name='identification_he',
            field=models.TextField(blank=True, verbose_name='סימני זיהוי'),
        ),
        migrations.AddField(
            model_name='species',
            name='introduction_route_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='דרך ההגעה לים התיכון (אנגלית)'),
        ),
        migrations.AddField(
            model_name='species',
            name='introduction_route_he',
            field=models.CharField(blank=True, max_length=200, verbose_name='דרך ההגעה לים התיכון'),
        ),
        migrations.AddField(
            model_name='species',
            name='last_record_place_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='מקום התצפית האחרונה (אנגלית)'),
        ),
        migrations.AddField(
            model_name='species',
            name='last_record_place_he',
            field=models.CharField(blank=True, max_length=200, verbose_name='מקום התצפית האחרונה'),
        ),
        migrations.AddField(
            model_name='species',
            name='med_status_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='מעמד בים התיכון (אנגלית)'),
        ),
        migrations.AddField(
            model_name='species',
            name='med_status_he',
            field=models.CharField(blank=True, max_length=200, verbose_name='מעמד בים התיכון'),
        ),
        migrations.AddField(
            model_name='species',
            name='native_range_en',
            field=models.TextField(blank=True, verbose_name='תפוצה מקורית (אנגלית)'),
        ),
        migrations.AddField(
            model_name='species',
            name='native_range_he',
            field=models.TextField(blank=True, verbose_name='תפוצה מקורית'),
        ),
        migrations.AddField(
            model_name='species',
            name='similar_species_en',
            field=models.TextField(blank=True, verbose_name='מינים דומים (אנגלית)'),
        ),
        migrations.AddField(
            model_name='species',
            name='similar_species_he',
            field=models.TextField(blank=True, verbose_name='מינים דומים'),
        ),
        migrations.AddField(
            model_name='species',
            name='sources',
            field=models.TextField(blank=True, verbose_name='מקורות (קישור בכל שורה)'),
        ),
    ]
