# Generated by Django 5.2.17 on 2026-10-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0053_gallery_species_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonfamily',
            name='identification_en',
            field=models.TextField(blank=True, verbose_name='סימני זיהוי (אנגלית)'),
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='identification_he',
            field=models.TextField(blank=True, verbose_name='סימני זיהוי'),
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='sources',
            field=models.TextField(blank=True, verbose_name='מקורות (קישור בכל שורה)'),
        ),
        migrations.AddField(
            model_name='taxongenus',
            name='identification_en',
            field=models.TextField(blank=True, verbose_name='סימני זיהוי (אנגלית)'),
        ),
        migrations.AddField(
            model_name='taxongenus',
            name='identification_he',
            field=models.TextField(blank=True, verbose_name='סימני זיהוי'),
        ),
        migrations.AddField(
            model_name='taxongenus',
            name='sources',
            field=models.TextField(blank=True, verbose_name='מקורות (קישור בכל שורה)'),
        ),
        migrations.AddField(
            model_name='taxonorder',
            name='identification_en',
            field=models.TextField(blank=True, verbose_name='סימני זיהוי (אנגלית)'),
        ),
        migrations.AddField(
            model_name='taxonorder',
            name='identification_he',
            field=models.TextField(blank=True, verbose_name='סימני זיהוי'),
        ),
        migrations.AddField(
            model_name='taxonorder',
            name='sources',
            field=models.TextField(blank=True, verbose_name='מקורות (קישור בכל שורה)'),
        ),
    ]
