# Generated by Django 5.2.17 on 2026-10-07 05:33

import django.core.validators
import observations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0056_english_common_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongenus',
            name='identification_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='כיתוב לקובץ הזיהוי'),
        ),
        migrations.AddField(
            model_name='taxongenus',
            name='identification_file',
            field=models.FileField(blank=True, help_text='תרשים, לוח תמונות או מפתח לזיהוי המינים בסוג: PDF או תמונה (JPG, PNG, WebP, GIF), עד 15MB.', upload_to='identification/genera/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif']), observations.models.validate_identification_file_size], verbose_name='קובץ זיהוי (PDF או תמונה)'),
        ),
        migrations.AddField(
            model_name='taxongenus',
            name='identification_source',
            field=models.CharField(blank=True, help_text='למשל: שם המחבר, הספר או המאמר שממנו נלקח התרשים.', max_length=300, verbose_name='מקור קובץ הזיהוי'),
        ),
    ]
