# Generated by Django 5.2.17 on 2026-10-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0057_genus_identification_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongenus',
            name='identification_caption_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='כיתוב לקובץ הזיהוי (אנגלית)'),
        ),
    ]
