# Generated by Django 5.2.17 on 2026-10-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0058_genus_identification_caption_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='observations.divetrip', verbose_name='מסע צלילה'),
        ),
    ]
