# Generated by Django 5.2.17 on 2026-10-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0059_sample_trip_optional_for_taxon_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='reference_link',
            field=models.URLField(blank=True, max_length=300, verbose_name='קישור עזר (תמונה / WoRMS)'),
        ),
    ]
