# Generated by Django 5.2.17 on 2026-10-08 10:43

from django.db import migrations, models


def seed_codes(apps, schema_editor):
    # Give every existing region and photographer their code, deterministically (oldest first),
    # so the suggested trip codes are the same on every environment.
    from observations.trip_naming import region_code_for, photographer_letter_for, default_photographer_username
    Region = apps.get_model('observations', 'Region')
    Profile = apps.get_model('observations', 'Profile')
    taken = set()
    regions = list(Region.objects.select_related('country', 'sea').order_by('pk'))
    # the two places that already have an established letter claim it first
    for region in sorted(regions, key=lambda r: r.name_en not in ('Akhziv', 'Eilat')):
        israel_med = (region.country.name_en or '').strip() == 'Israel' and 'Mediterranean' in (region.sea.name_en or '')
        code = region_code_for(region.name_en, region.name, israel_med, taken)
        taken.add(code)
        Region.objects.filter(pk=region.pk).update(trip_code=code)
    letters = set()
    for profile in Profile.objects.select_related('user').order_by('pk'):
        if profile.user.username == default_photographer_username():
            continue
        letter = photographer_letter_for(profile.first_name_en, profile.user.username, letters)
        letters.add(letter)
        Profile.objects.filter(pk=profile.pk).update(trip_code=letter)


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0060_species_reference_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trip_code',
            field=models.CharField(blank=True, help_text='האות שמופיעה בתחילת סימון מסע של הצלם. ריק = בלי אות (בעל האתר).', max_length=4, verbose_name='אות הצלם בסימון מסעות'),
        ),
        migrations.AddField(
            model_name='region',
            name='trip_code',
            field=models.CharField(blank=True, help_text='משמשת בסימון המסע (למשל I26Aug). אם נשאר ריק, נקבעת אוטומטית בהוספת המסע הראשון באזור.', max_length=6, verbose_name='אות/ות האזור בסימון מסעות'),
        ),
        migrations.RunPython(seed_codes, migrations.RunPython.noop),
    ]
