# Generated by Django 5.2.17 on 2026-10-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0062_unify_coryphellina_sp_b_and_fix_philippines'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, verbose_name='מזהה')),
                ('lang', models.CharField(max_length=2, verbose_name='שפה')),
                ('content', models.TextField(verbose_name='תוכן')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן')),
            ],
            options={
                'verbose_name': 'טקסט בדף הבית',
                'verbose_name_plural': 'טקסטים בדף הבית',
                'constraints': [models.UniqueConstraint(fields=('key', 'lang'), name='unique_home_text')],
            },
        ),
    ]
